# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ddareunge_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ddareunge_iOS

  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON', '~> 4.0'

end
